# Generated by Django 6.0 on 2026-01-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(blank=True, default='movie_images/default.jpg', null=True, upload_to='movie_images/'),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='typ',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
