# Generated by Django 6.0 on 2026-01-07 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
