# Generated by Django 6.0 on 2026-01-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_item_item_desc_alter_item_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
